export const renderHome = (): string => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>jido-cartographer</title>
<style>
:root{color-scheme:dark;--ink:#f5f7fa;--muted:#9da9b8;--panel:#111923;--line:#263445;--cyan:#55d6be;--amber:#ffcb6b;--red:#ff6b7a}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#183249 0,#091018 38%,#060b10 100%);color:var(--ink);font:15px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;min-height:100vh}main{width:min(1180px,calc(100% - 32px));margin:auto;padding:54px 0 80px}header{display:grid;grid-template-columns:1fr auto;gap:24px;align-items:end;margin-bottom:34px}h1{font-size:clamp(32px,6vw,72px);line-height:.9;letter-spacing:-.07em;margin:0}.accent{color:var(--cyan)}.eyebrow{color:var(--amber);text-transform:uppercase;letter-spacing:.18em;font-size:12px;margin-bottom:14px}.tagline{max-width:650px;color:var(--muted);font-size:16px;margin:20px 0 0}.beam{border:1px solid var(--line);border-radius:999px;padding:9px 14px;color:var(--cyan);white-space:nowrap}form{display:grid;grid-template-columns:1fr 180px auto;gap:10px;background:rgba(17,25,35,.86);border:1px solid var(--line);border-radius:16px;padding:14px;box-shadow:0 22px 80px #0008}input,button{font:inherit;border-radius:10px;border:1px solid var(--line);padding:13px 14px}input{background:#071019;color:var(--ink);min-width:0}button{background:var(--cyan);color:#04110e;font-weight:800;cursor:pointer}button:disabled{opacity:.45;cursor:wait}.status{min-height:34px;padding:18px 3px;color:var(--muted)}.status.error{color:var(--red)}.grid{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.card,.panel{background:rgba(17,25,35,.8);border:1px solid var(--line);border-radius:14px}.card{padding:16px}.metric{font-size:26px;color:var(--cyan);font-weight:700}.label{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.12em}.panels{display:grid;grid-template-columns:1fr 1.6fr;gap:14px;margin-top:14px}.panel{padding:18px;overflow:hidden}.panel h2{margin:0 0 14px;font-size:14px;color:var(--amber);letter-spacing:.1em;text-transform:uppercase}.language{display:grid;grid-template-columns:100px 1fr 46px;gap:9px;align-items:center;margin:8px 0}.bar{height:8px;background:#203040;border-radius:99px;overflow:hidden}.bar i{display:block;height:100%;background:linear-gradient(90deg,var(--cyan),#75a7ff)}.scroll{max-height:420px;overflow:auto}table{border-collapse:collapse;width:100%;font-size:12px}th,td{text-align:left;border-bottom:1px solid #1d2a37;padding:9px 7px;vertical-align:top}th{position:sticky;top:0;background:var(--panel);color:var(--muted)}td:first-child{word-break:break-all}.edges{display:grid;gap:7px}.edge{padding:8px 10px;background:#09121b;border-radius:8px;color:var(--muted);word-break:break-all}.edge b{color:var(--ink)}.hidden{display:none}@media(max-width:800px){header{grid-template-columns:1fr}.beam{justify-self:start}form{grid-template-columns:1fr}.grid{grid-template-columns:repeat(2,1fr)}.panels{grid-template-columns:1fr}}
</style>
</head>
<body>
<main>
<header><div><div class="eyebrow">Jido 2.x × BEAM concurrency</div><h1>codebase<br><span class="accent">cartographer</span></h1><p class="tagline">One lightweight Jido agent per source file. Deterministic facts fan out across BEAM processes, then fold into a measured code map.</p></div><div class="beam">● no LLM required</div></header>
<form id="form"><input id="url" name="url" required value="https://github.com/agentjido/jido" aria-label="Public GitHub repository URL"><input id="ref" name="ref" value="v2.3.3" aria-label="Git ref"><button id="submit">Index repo</button></form>
<div id="status" class="status">Ready for a public GitHub repository.</div>
<section id="results" class="hidden">
<div id="metrics" class="grid"></div>
<div class="panels"><div class="panel"><h2>Languages</h2><div id="languages"></div><h2 style="margin-top:24px">Dependency edges</h2><div id="edges" class="edges scroll"></div></div><div class="panel"><h2>Source files</h2><div class="scroll"><table><thead><tr><th>Path</th><th>Lang</th><th>Lines</th><th>Bytes</th><th>Symbols</th></tr></thead><tbody id="files"></tbody></table></div></div></div>
</section>
</main>
<script type="module">
const form=document.querySelector('#form'),button=document.querySelector('#submit'),status=document.querySelector('#status'),results=document.querySelector('#results');
const text=(tag,value,cls)=>{const el=document.createElement(tag);if(cls)el.className=cls;el.textContent=value;return el};
const metric=(value,label)=>{const card=text('div','', 'card');card.append(text('div',value,'metric'),text('div',label,'label'));return card};
const render=data=>{const r=data.result,s=r.summary,t=r.timing;const metrics=document.querySelector('#metrics');metrics.replaceChildren(metric(s.files,'files / agents'),metric(s.lines.toLocaleString(),'lines'),metric(s.symbols.toLocaleString(),'symbols'),metric(s.dependencies.toLocaleString(),'edges'),metric(t.analysis_ms+' ms','agent analysis'),metric(t.total_ms+' ms','total'));
const languages=document.querySelector('#languages');languages.replaceChildren(...s.languages.map(l=>{const row=text('div','', 'language'),bar=text('div','', 'bar'),fill=text('i','');fill.style.width=Math.max(3,l.files/s.files*100)+'%';bar.append(fill);row.append(text('span',l.language),bar,text('span',String(l.files)));return row}));
const edges=document.querySelector('#edges');const shown=r.edges.slice(0,120);edges.replaceChildren(...shown.map(e=>{const row=text('div','', 'edge');row.append(text('b',e.from),document.createTextNode(' → '+e.to));return row}),...(r.edges.length>shown.length?[text('div','+'+(r.edges.length-shown.length)+' more','edge')]:[]));
const files=document.querySelector('#files');files.replaceChildren(...r.files.map(f=>{const tr=document.createElement('tr');[f.path,f.language,f.lines,f.bytes,f.symbols.slice(0,5).join(', ')].forEach(v=>tr.append(text('td',String(v))));return tr}));results.classList.remove('hidden')};
const poll=async id=>{for(let i=0;i<90;i++){const res=await fetch('/api/results/'+encodeURIComponent(id)),data=await res.json();if(data.status==='complete'){status.textContent='Mapped '+data.result.repository.owner+'/'+data.result.repository.repo+' at '+data.result.repository.ref;render(data);return}if(data.status==='failed')throw new Error(data.error||'Index failed');status.textContent='Agents running… '+(i+1);await new Promise(r=>setTimeout(r,750))}throw new Error('Index timed out while waiting for a result')};
form.addEventListener('submit',async event=>{event.preventDefault();button.disabled=true;results.classList.add('hidden');status.className='status';status.textContent='Fetching bounded snapshot…';try{const response=await fetch('/api/index',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:form.url.value,ref:form.ref.value})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');await poll(data.id)}catch(error){status.className='status error';status.textContent=error instanceof Error?error.message:String(error)}finally{button.disabled=false}});
</script>
</body>
</html>`;
